/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as BackofficeIndexRouteImport } from './routes/backoffice.index'
import { Route as BackofficeLoginRouteImport } from './routes/backoffice.login'
import { Route as SegmentosIndexRouteImport } from './routes/segmentos.index'
import { Route as SegmentosSlugRouteImport } from './routes/segmentos.$slug'
import { Route as SolucoesIndexRouteImport } from './routes/solucoes.index'
import { Route as SolucoesSlugRouteImport } from './routes/solucoes.$slug'
import { Route as ApiPublicSeedAdminRouteImport } from './routes/api/public/seed-admin'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const BackofficeIndexRoute = BackofficeIndexRouteImport.update({
  id: '/backoffice/',
  path: '/backoffice/',
  getParentRoute: () => rootRouteImport,
} as any)
const BackofficeLoginRoute = BackofficeLoginRouteImport.update({
  id: '/backoffice/login',
  path: '/backoffice/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SegmentosIndexRoute = SegmentosIndexRouteImport.update({
  id: '/segmentos/',
  path: '/segmentos/',
  getParentRoute: () => rootRouteImport,
} as any)
const SegmentosSlugRoute = SegmentosSlugRouteImport.update({
  id: '/segmentos/$slug',
  path: '/segmentos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SolucoesIndexRoute = SolucoesIndexRouteImport.update({
  id: '/solucoes/',
  path: '/solucoes/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolucoesSlugRoute = SolucoesSlugRouteImport.update({
  id: '/solucoes/$slug',
  path: '/solucoes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSeedAdminRoute = ApiPublicSeedAdminRouteImport.update({
  id: '/api/public/seed-admin',
  path: '/api/public/seed-admin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/backoffice/login': typeof BackofficeLoginRoute
  '/segmentos/$slug': typeof SegmentosSlugRoute
  '/solucoes/$slug': typeof SolucoesSlugRoute
  '/backoffice/': typeof BackofficeIndexRoute
  '/segmentos/': typeof SegmentosIndexRoute
  '/solucoes/': typeof SolucoesIndexRoute
  '/api/public/seed-admin': typeof ApiPublicSeedAdminRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/backoffice/login': typeof BackofficeLoginRoute
  '/segmentos/$slug': typeof SegmentosSlugRoute
  '/solucoes/$slug': typeof SolucoesSlugRoute
  '/backoffice': typeof BackofficeIndexRoute
  '/segmentos': typeof SegmentosIndexRoute
  '/solucoes': typeof SolucoesIndexRoute
  '/api/public/seed-admin': typeof ApiPublicSeedAdminRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/backoffice/login': typeof BackofficeLoginRoute
  '/segmentos/$slug': typeof SegmentosSlugRoute
  '/solucoes/$slug': typeof SolucoesSlugRoute
  '/backoffice/': typeof BackofficeIndexRoute
  '/segmentos/': typeof SegmentosIndexRoute
  '/solucoes/': typeof SolucoesIndexRoute
  '/api/public/seed-admin': typeof ApiPublicSeedAdminRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/backoffice/login'
    | '/segmentos/$slug'
    | '/solucoes/$slug'
    | '/backoffice/'
    | '/segmentos/'
    | '/solucoes/'
    | '/api/public/seed-admin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/backoffice/login'
    | '/segmentos/$slug'
    | '/solucoes/$slug'
    | '/backoffice'
    | '/segmentos'
    | '/solucoes'
    | '/api/public/seed-admin'
  id:
    | '__root__'
    | '/'
    | '/sitemap.xml'
    | '/backoffice/login'
    | '/segmentos/$slug'
    | '/solucoes/$slug'
    | '/backoffice/'
    | '/segmentos/'
    | '/solucoes/'
    | '/api/public/seed-admin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BackofficeLoginRoute: typeof BackofficeLoginRoute
  SegmentosSlugRoute: typeof SegmentosSlugRoute
  SolucoesSlugRoute: typeof SolucoesSlugRoute
  BackofficeIndexRoute: typeof BackofficeIndexRoute
  SegmentosIndexRoute: typeof SegmentosIndexRoute
  SolucoesIndexRoute: typeof SolucoesIndexRoute
  ApiPublicSeedAdminRoute: typeof ApiPublicSeedAdminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backoffice/': {
      id: '/backoffice/'
      path: '/backoffice'
      fullPath: '/backoffice/'
      preLoaderRoute: typeof BackofficeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backoffice/login': {
      id: '/backoffice/login'
      path: '/backoffice/login'
      fullPath: '/backoffice/login'
      preLoaderRoute: typeof BackofficeLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/segmentos/': {
      id: '/segmentos/'
      path: '/segmentos'
      fullPath: '/segmentos/'
      preLoaderRoute: typeof SegmentosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/segmentos/$slug': {
      id: '/segmentos/$slug'
      path: '/segmentos/$slug'
      fullPath: '/segmentos/$slug'
      preLoaderRoute: typeof SegmentosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes/': {
      id: '/solucoes/'
      path: '/solucoes'
      fullPath: '/solucoes/'
      preLoaderRoute: typeof SolucoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes/$slug': {
      id: '/solucoes/$slug'
      path: '/solucoes/$slug'
      fullPath: '/solucoes/$slug'
      preLoaderRoute: typeof SolucoesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/seed-admin': {
      id: '/api/public/seed-admin'
      path: '/api/public/seed-admin'
      fullPath: '/api/public/seed-admin'
      preLoaderRoute: typeof ApiPublicSeedAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BackofficeLoginRoute: BackofficeLoginRoute,
  SegmentosSlugRoute: SegmentosSlugRoute,
  SolucoesSlugRoute: SolucoesSlugRoute,
  BackofficeIndexRoute: BackofficeIndexRoute,
  SegmentosIndexRoute: SegmentosIndexRoute,
  SolucoesIndexRoute: SolucoesIndexRoute,
  ApiPublicSeedAdminRoute: ApiPublicSeedAdminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
